/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *                                                                           *
 * A simple AA PDF class by Ivan Heredia de la Cruz on 4/25/16.              *
 *****************************************************************************/

#ifndef MYPDF
#define MYPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "TComplex.h"


Double_t MLb = 5.61951;
Double_t MJPsi = 3.096916;
Double_t MProton = 0.938272046;
Double_t MKaon = 0.493677;


Double_t MLb2 = MLb*MLb;
Double_t MLb4 = MLb2*MLb2;
Double_t MJPsi2 = MJPsi*MJPsi;
Double_t MJPsi4 = MJPsi2*MJPsi2;
Double_t MJPsi4mTwoMJPsi2MLb2pMLb4 = MJPsi4 - 2.*MJPsi2*MLb2 + MLb4;
Double_t TwoMJPsi2pTwoMLb2 = 2.*(MJPsi2 + MLb2);
Double_t InvTwoMLb = 1./(2.*MLb);

Double_t MProton2 = MProton*MProton;
Double_t MProton4 = MProton2*MProton2;
Double_t MKaon2 = MKaon*MKaon;
Double_t MKaon4 = MKaon2*MKaon2;
Double_t MKaon4mTwoMKaon2MProton2pMProton4 = MKaon4 - 2.*MKaon2*MProton2 + MProton4;
Double_t TwoMKaon2pTwoMProton2 = 2.*(MKaon2 + MProton2);

Double_t M1600 = 1.600 ;
Double_t G1600 = 0.150;
Double_t M1670 = 1.670;
Double_t G1670 = 0.035;

Double_t dRad = 3.0;


class myPDF : public RooAbsPdf {
public:
  myPDF() {} ;
  myPDF(const char *name, const char *title,
	      RooAbsReal& _mKp,
	      RooAbsReal& _cLb,
	      RooAbsReal& _cJ,
	      RooAbsReal& _cLs,
	      RooAbsReal& _phiMu,
	      RooAbsReal& _phiK,
           RooAbsReal& _a1600L0S1,
           RooAbsReal& _b1600L0S1,
           RooAbsReal& _a1600L1S1,
           RooAbsReal& _b1600L1S1,
           RooAbsReal& _a1600L1S3,
           RooAbsReal& _b1600L1S3,
           RooAbsReal& _a1600L2S3,
           RooAbsReal& _b1600L2S3,
           RooAbsReal& _a1670L0S1,
           RooAbsReal& _b1670L0S1,
           RooAbsReal& _a1670L1S1,
           RooAbsReal& _b1670L1S1,
           RooAbsReal& _a1670L1S3,
           RooAbsReal& _b1670L1S3,
           RooAbsReal& _a1670L2S3,
           RooAbsReal& _b1670L2S3);
  myPDF(const myPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new myPDF(*this,newname); }
  inline virtual ~myPDF() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
    
    Double_t cWignerDLb(string helLb, string helLs, string helJ) const ;
    TComplex cWignerDLsSpinOneHalf(string helLs, string help) const ;
    TComplex cWignerDJ(string helJ, string helDmu) const ;

    TComplex HLb1600(string helLs, string helJ) const ;
    TComplex HLb1670(string helLs, string helJ) const ;
    Double_t HLs1600(string help) const ;
    Double_t HLs1670(string help) const ;

    Double_t Pmom(Double_t mkp) const ;
    Double_t Qmom(Double_t mkp) const ;
    Double_t PhiPHSP(Double_t mkp) const ;

    Double_t BlattWeisskopf(Int_t Lmin, Double_t q, Double_t q0, Double_t D = dRad) const ;
    Double_t BWGamma(Double_t RMass, Double_t RGamma, Int_t Lmin, Double_t D = dRad) const ;
    TComplex BW(Double_t RMass, Double_t RGamma, Int_t Lmin, Double_t D = dRad) const ;
    TComplex RFunction(Double_t RMass, Double_t RGamma, Int_t LminLb, Int_t LminLs, Double_t D = dRad) const ;

    TComplex Cterm(string helLs, string helJ, string help) const ;
    TComplex Cfterm(string helLs, string helJ, string help, string helDmu) const ;
    TComplex ME(string helLb, string help, string helDmu) const ;
    TComplex ME2() const ;
    TComplex PDF() const ;
    
    
protected:

  RooRealProxy mKp ;
  RooRealProxy cLb ;
  RooRealProxy cJ ;
  RooRealProxy cLs ;
  RooRealProxy phiMu ;
  RooRealProxy phiK ;
    RooRealProxy a1600L0S1 ;
    RooRealProxy b1600L0S1 ;
    RooRealProxy a1600L1S1 ;
    RooRealProxy b1600L1S1 ;
    RooRealProxy a1600L1S3 ;
    RooRealProxy b1600L1S3 ;
    RooRealProxy a1600L2S3 ;
    RooRealProxy b1600L2S3 ;
    RooRealProxy a1670L0S1 ;
    RooRealProxy b1670L0S1 ;
    RooRealProxy a1670L1S1 ;
    RooRealProxy b1670L1S1 ;
    RooRealProxy a1670L1S3 ;
    RooRealProxy b1670L1S3 ;
    RooRealProxy a1670L2S3 ;
    RooRealProxy b1670L2S3 ;
  
    
  Double_t evaluate() const ;
    

private:

  ClassDef(myPDF,1) // Your description goes here...
};
 
#endif
