/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ANGLES_CONTOUR
#define ANGLES_CONTOUR

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class Angles_contour : public RooAbsPdf {
public:
  Angles_contour() {} ; 
  Angles_contour(const char *name, const char *title,
		 RooAbsReal& _cosMuMu,
		 RooAbsReal& _phi
		 );
  Angles_contour(const Angles_contour& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Angles_contour(*this,newname); }
  inline virtual ~Angles_contour() { }

protected:

  RooRealProxy cosMuMu ;
  RooRealProxy phi ;
  
  Double_t evaluate() const ;

private:

  ClassDef(Angles_contour,1) // Your description goes here...
};
 
#endif
