/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "Angles_contour.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(Angles_contour) 

 Angles_contour::Angles_contour(const char *name, const char *title, 
				RooAbsReal& _cosMuMu,
				RooAbsReal& _phi
				) :
  RooAbsPdf(name,title), 
  cosMuMu("cosMuMu","cosMuMu",this,_cosMuMu),
  phi("phi","phi",this,_phi)
{ 
} 


 Angles_contour::Angles_contour(const Angles_contour& other, const char* name) :  
   RooAbsPdf(other,name), 
   cosMuMu("cosMuMu",this,other.cosMuMu),
   phi("phi",this,other.phi)
 { 
 } 



 Double_t Angles_contour::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   if (fabs(cosMuMu) > 1  ||  fabs(phi) > TMath::Pi())
     return 0;
   else
     return 1;
 } 
