/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "Dalitz_contour.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(Dalitz_contour) 

 Dalitz_contour::Dalitz_contour(const char *name, const char *title, 
				RooAbsReal& _mKP,
				RooAbsReal& _mPsiP,
				const Bool_t _massSquared,
				const TString& _psi_nS
				) :
  RooAbsPdf(name,title), 
  mKP("mKP","mKP",this,_mKP),
  mPsiP("mPsiP","mPsiP",this,_mPsiP),
  massSquared(_massSquared),
  psi_nS(_psi_nS)
{ 
} 


 Dalitz_contour::Dalitz_contour(const Dalitz_contour& other, const char* name) :  
   RooAbsPdf(other,name), 
   mKP("mKP",this,other.mKP),
   mPsiP("mPsiP",this,other.mPsiP),
   massSquared(other.massSquared),
   psi_nS(other.psi_nS)
 { 
 } 



 Double_t Dalitz_contour::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

   return Dalitz_contour_host(mKP, mPsiP, massSquared, psi_nS.Atoi());
 } 
