/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef EFFMASSES
#define EFFMASSES

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

#include "RooRealVar.h"
 
class effMasses : public RooAbsPdf {
public:
  effMasses() {} ; 
  effMasses(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _y,
	      RooRealVar* _x2,
	      RooRealVar* _y2,
	      RooAbsPdf* _effDalitz);
  effMasses(const effMasses& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new effMasses(*this,newname); }
  inline virtual ~effMasses() { }

protected:

  RooRealProxy x ;
  RooRealProxy y ;
  //mutable RooRealProxy y2 ;
  //mutable RooRealProxy y2 ;
  RooRealVar* x2 ;
  RooRealVar* y2 ;
  RooAbsPdf* effDalitz ;
  
  Double_t evaluate() const ;

private:

  ClassDef(effMasses,1) // Your description goes here...
};
 
#endif
