/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "sqDalitz_contour.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(sqDalitz_contour) 

 sqDalitz_contour::sqDalitz_contour(const char *name, const char *title, 
				RooAbsReal& _mKP,
				RooAbsReal& _cosKstar,
				const Bool_t _massSquared,
				const Int_t& _psi_nS
				) :
  RooAbsPdf(name,title), 
  mKP("mKP","mKP",this,_mKP),
  cosKstar("cosKstar","cosKstar",this,_cosKstar),
  massSquared(_massSquared),
  psi_nS(_psi_nS)
{ 
} 


 sqDalitz_contour::sqDalitz_contour(const sqDalitz_contour& other, const char* name) :  
   RooAbsPdf(other,name), 
   mKP("mKP",this,other.mKP),
   cosKstar("cosKstar",this,other.cosKstar),
   massSquared(other.massSquared),
   psi_nS(other.psi_nS)
 { 
 } 



 Double_t sqDalitz_contour::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   if (fabs(cosKstar) > 1)
     return 0 ;


   Double_t MPsi_nS = 0; 
   if (psi_nS == 1) 
     MPsi_nS = MJpsi;
   else if (psi_nS == 2)
     MPsi_nS = MPsi2S;
   else {
     cout <<"psi_nS = " <<psi_nS <<" not allowed at the moment." <<endl;
     return kFALSE;
   }

   Double_t mKP_1 = mKP;
   if (massSquared)
     mKP_1 = TMath::Sqrt( mKP );

   if ((mKP_1 < MKaon + MPion) || (mKP_1 > MBd - MPsi_nS))
     return 0 ;
   
   
   return 1. ;
 }
